<?php

use GuzzleHttp\Client;
use GuzzleHttp\Exception\RequestException;

/**
 * Implements hook_theme().
 */
  function crypto_tracker_theme($existing, $type, $theme, $path) {
    return [
       'crypto_tracker_block' => [
          'variables' => ['cryptos' => NULL],
          'theme' => 'crypto-tracker-block',
      ],

      'crypto_results' => [
        'variables' => ['cryptos' => NULL],
        'theme' => 'crypto-results',
      ],
    ];
  }

  /**
    * Implements hook_cron().
    */
  function crypto_tracker_cron() {
    \Drupal::logger('crypto_tracker')->notice('Radi na svakih 5 minuta');
      $client = new Client();
      $limit = 0;
      $coins = [
        'id' => ' ',
        'name' => ' ',
        'symbol' => ' ',
        'rank' => ' ',
        ];

      $response = $client->get('https://api.coinpaprika.com/v1/coins');
      $result = json_decode($response->getBody()->getContents(), TRUE);
      foreach($result as $coins) {
      $coin[$coins['id']] = [
        'id' => $coins['id'],
        'name' => $coins['name'],
        'symbol' => $coins['symbol'],
        'rank' => $coins['rank']
     ];
      if (++$limit == 100) break;

     $connection = \Drupal::service('database');
     foreach($coin as $item) {
      $query = $connection->update('crypto_currency');
      $query->fields([
      'coin_id' => $item['id'],
      'name' => $item['name'],
      'symbol' => $item['symbol'],
      'rank' => $item['rank'],
     ]);

     $query->condition('coin_id', $item['id'], 'IN');

     $query->execute();
    }

   }

 }




